modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/tracerxbrhd/innutrient/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/tracerxbrhd/innutrient"
logoFile = "innutrient_icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "u_api"
type = "required"
versionRange = "${u_api_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "farmersdelight"
type = "optional"
versionRange = "[1.2.8,)"
ordering = "AFTER"
side = "BOTH"
